![Ironhack logo](https://user-images.githubusercontent.com/23629340/40541063-a07a0a8a-601a-11e8-91b5-2f13e4e6b441.png)

# 01 | Exploratory Data Analysis

*Project 1 — SQL: From Data to Insight*

**Team:**
**Dataset:**

---

Understanding your data before you design anything. You cannot decide which tables you need until you know which columns repeat, which are broken, and which identify a row.

> **Done when:** you can name the 3+ tables you are going to build, you have written down at least 2 research questions, and you know every data-quality problem notebook 02 will have to fix.

The sections below are a suggested route, not a form to fill in. Add sections, drop them, reorder them — what is graded is the analysis, not whether you kept the scaffold.

---
## 0. Setup

In [1]:
import pandas as pd
import numpy as np

---
## 1. Load the raw data

The Global Impacts Dataset of Invasive Alien Species (GIDIAS) has first been published on the 21. of Mai 2025 by Springer Natur and authored by S. Bacher et al.  (https://doi.org/10.6084/m9.figshare.27908838)

In [3]:
df_raw = pd.read_csv("../data/raw/GIDIAS_20250417_machine_read.csv")

---
## 2. First look

The first step is to take a closer look at the raw data to assess the overall shape of the dataset, examine the types of data it contains, and identify any further relevant information or patterns that may require closer investigation.

In [14]:
df_raw.shape

(22865, 90)

The dataset contains 22865 rows and 90 columns.

In [30]:
df_raw.info()

<class 'pandas.DataFrame'>
RangeIndex: 22865 entries, 0 to 22864
Data columns (total 90 columns):
 #   Column                              Non-Null Count  Dtype
---  ------                              --------------  -----
 0   rowID                               22865 non-null  int64
 1   UniqueID                            22865 non-null  str
 2   IAS.Species.Name                    22865 non-null  str
 3   Verified.Name.GBIF.Taxon            22346 non-null  str
 4   GBIF.scientificName.with.author     21574 non-null  str
 5   Genus                               22308 non-null  str
 6   Family                              22281 non-null  str
 7   Order                               22201 non-null  str
 8   Class                               20943 non-null  str
 9   Phylum                              22310 non-null  str
 10  Kingdom                             22339 non-null  str
 11  IAS.Taxon                           22865 non-null  str
 12  IAS.Functional.Group                19687 non-null  str
 13  native.range.of.IAS                 5453 non-null   str
 14  Reference                           22865 non-null  str
 15  Text.excerpt                        18718 non-null  str
 16  DOI                                 6358 non-null   str
 17  Assessor                            22865 non-null  str
 18  Year                                22193 non-null  float64
 19  Year.of.impact                      2954 non-null   float64
 20  Type.of.source                      21147 non-null  str
 21  Peer.reviewed                       22865 non-null  bool
 22  Language                            22101 non-null  str
 23  Methodology.details                 20084 non-null  str
 24  Region                              22734 non-null  str
 25  Country.Location                    21616 non-null  str
 26  Island                              8002 non-null   str
 27  Island.k                            22865 non-null  bool
 28  Protected.area                      3233 non-null   str
 29  Protected.area.k                    22865 non-null  bool
 30  Realm                               22792 non-null  str
 31  Units.of.Analysis.clean             19543 non-null  str
 32  Spatial.scale                       18365 non-null  str
 33  Affected.native.species.Details     14358 non-null  str
 34  Affected.native.species.Taxon       14380 non-null  str
 35  Affected.ecosystem.property         13317 non-null  str
 36  investigated.level.of.organization  10565 non-null  str
 37  mechanism.Nature.clean              14069 non-null  str
 38  direction.Nature                    14674 non-null  str
 39  direct.or.indirect.Nature           10372 non-null  str
 40  global.extinction                   22865 non-null  bool
 41  magnitude.Nature                    11881 non-null  float64
 42  affected.NCP.clean                  7294 non-null   str
 43  details.NCP                         3689 non-null   str
 44  direction.NCP                       7144 non-null   str
 45  magnitude.NCP                       2965 non-null   str
 46  affected.CWB.clean                  3438 non-null   str
 47  details.CWB                         2705 non-null   str
 48  direction.CWB                       3400 non-null   str
 49  magnitude.CWB                       1595 non-null   str
 50  magnitude.CWB.details               193 non-null    str
 51  IPLC                                784 non-null    str
 52  UoA.Dry                             22865 non-null  bool
 53  UoA.Boreal                          22865 non-null  bool
 54  UoA.Mediterranean                   22865 non-null  bool
 55  UoA.Tundra                          22865 non-null  bool
 56  UoA.Savanna                         22865 non-null  bool
 57  UoA.Grassland                       22865 non-null  bool
 58  UoA.Desert                          22865 non-null  bool
 59  UoA.Urban                           22865 non-null  bool
 60  UoA.Cultivated                      22865 non-null  bool
 61  UoA.Aquaculture                     22865 non-null  bool
 62  UoA.Wetland                         22865 non-null  bool
 63  UoA.Surface                         22865 non-null  bool
 64  UoA.Shelf                           22865 non-null  bool
 65  UoA.Ocean                           22865 non-null  bool
 66  UoA.Coastal                         22865 non-null  bool
 67  NCP.Habitat                         22865 non-null  bool
 68  NCP.Pollination                     22865 non-null  bool
 69  NCP.AirQuality                      22865 non-null  bool
 70  NCP.Climate                         22865 non-null  bool
 71  NCP.OceanAcid                       22865 non-null  bool
 72  NCP.Freshwater                      22865 non-null  bool
 73  NCP.WaterQuality                    22865 non-null  bool
 74  NCP.Soils                           22865 non-null  bool
 75  NCP.Hazards                         22865 non-null  bool
 76  NCP.BiolProcess                     22865 non-null  bool
 77  NCP.Energy                          22865 non-null  bool
 78  NCP.Food                            22865 non-null  bool
 79  NCP.Materials                       22865 non-null  bool
 80  NCP.Medicinal                       22865 non-null  bool
 81  NCP.Learning                        22865 non-null  bool
 82  NCP.Physical                        22865 non-null  bool
 83  NCP.Identities                      22865 non-null  bool
 84  NCP.Options                         22865 non-null  bool
 85  CWB.Safety                          22865 non-null  bool
 86  CWB.Assets                          22865 non-null  bool
 87  CWB.Health                          22865 non-null  bool
 88  CWB.Relations                       22865 non-null  bool
 89  CWB.Freedom                         22865 non-null  bool
dtypes: bool(42), float64(3), int64(1), str(44)
memory usage: 28.6 MB

A first look at the data shows that some columns contain null values. The data type of each column will be assessed in more detail later.

In [4]:
df_raw.head()

,rowID,UniqueID,IAS.Species.Name,Verified.Name.GBIF.Taxon,GBIF.scientificName.with.author,Genus,Family,Order,Class,Phylum,...,NCP.Medicinal,NCP.Learning,NCP.Physical,NCP.Identities,NCP.Options,CWB.Safety,CWB.Assets,CWB.Health,CWB.Relations,CWB.Freedom
0,1,AF_Fish_crayfish_00001,Gambusia affinis,Gambusia affinis,"Gambusia affinis (Baird & Girard, 1853)",Gambusia,Poeciliidae,Cyprinodontiformes,NaN,Chordata,...,False,False,False,False,False,False,False,False,False,False
1,2,AF_Fish_crayfish_00002,Onchorhynchus mykiss,Oncorhynchus mykiss,"Oncorhynchus mykiss (Walbaum, 1792)",Oncorhynchus,Salmonidae,Salmoniformes,NaN,Chordata,...,False,False,False,False,False,False,False,False,False,False
2,3,AF_Fish_crayfish_00003,Procambrus clarkii,Procambarus clarkii,"Procambarus clarkii (Girard, 1852)",Procambarus,Cambaridae,Decapoda,Malacostraca,Arthropoda,...,False,False,False,False,False,False,False,False,False,False
3,4,AF_Fish_crayfish_00004,Procambrus clarkii,Procambarus clarkii,"Procambarus clarkii (Girard, 1852)",Procambarus,Cambaridae,Decapoda,Malacostraca,Arthropoda,...,False,False,False,False,False,False,False,False,False,False
4,5,AF_Fish_crayfish_00005,Ctenopharyngodon idella,Ctenopharyngodon idella,"Ctenopharyngodon idella (Valenciennes, 1844)",Ctenopharyngodon,Cyprinidae,Cypriniformes,NaN,Chordata,...,False,False,False,False,False,False,False,False,False,False

In [28]:
df_raw.tail()

,rowID,UniqueID,IAS.Species.Name,Verified.Name.GBIF.Taxon,GBIF.scientificName.with.author,Genus,Family,Order,Class,Phylum,...,NCP.Medicinal,NCP.Learning,NCP.Physical,NCP.Identities,NCP.Options,CWB.Safety,CWB.Assets,CWB.Health,CWB.Relations,CWB.Freedom
22860,22861,ants_0840,Solenopsis invicta,Solenopsis invicta,"Solenopsis invicta Buren, 1972",Solenopsis,Formicidae,Hymenoptera,Insecta,Arthropoda,...,False,False,False,False,False,False,False,False,False,False
22861,22862,ants_0841,Solenopsis invicta,Solenopsis invicta,"Solenopsis invicta Buren, 1972",Solenopsis,Formicidae,Hymenoptera,Insecta,Arthropoda,...,False,False,False,False,False,False,False,False,False,False
22862,22863,ants_0842,Wasmannia auropunctata,Wasmannia auropunctata,"Wasmannia auropunctata (Roger, 1863)",Wasmannia,Formicidae,Hymenoptera,Insecta,Arthropoda,...,False,False,False,False,False,False,False,True,False,False
22863,22864,ants_0843,Wasmannia auropunctata,Wasmannia auropunctata,"Wasmannia auropunctata (Roger, 1863)",Wasmannia,Formicidae,Hymenoptera,Insecta,Arthropoda,...,False,False,False,False,False,False,True,False,False,False
22864,22865,ants_0844,Wasmannia auropunctata,Wasmannia auropunctata,"Wasmannia auropunctata (Roger, 1863)",Wasmannia,Formicidae,Hymenoptera,Insecta,Arthropoda,...,False,False,False,False,False,False,False,False,False,False

The first and last five rows of the dataset show us that each row can be uniquely identified by the species ID.

In [29]:
df_raw.dtypes

rowID                              int64
UniqueID                             str
IAS.Species.Name                     str
Verified.Name.GBIF.Taxon             str
GBIF.scientificName.with.author      str
                                   ...
CWB.Safety                          bool
CWB.Assets                          bool
CWB.Health                          bool
CWB.Relations                       bool
CWB.Freedom                         bool
Length: 90, dtype: object

In [26]:
col_types = df_raw.dtypes.reset_index()
col_types.columns = ["row", "type"]
col_types["type"].value_counts()

type
str        44
bool       42
float64     3
int64       1
Name: count, dtype: int64

44 columns are of type string, 42 are of type boolean, three are floats, and only one is an integer.

#### Summary: 2 - First look at the data 
The dataset contains 22,865 rows and 90 columns. Of these, 44 columns are of type string, 42 are of type boolean, three are floats, and only one is an integer.

The large number of boolean columns raises the question of whether all of them are necessary. To answer this question, the metadata will be examined more closely in Part 3.

Each row in the dataset represents one species. Each species can be identified by its unique ID (`UniqueID`). Other columns, such as the species name, may also uniquely identify a row.

---
## 3. Taking a look at the metadata

The metadata needs to be investigated, to see if all columns are relevant to the research questions.

In [32]:
df_meta = pd.read_excel("../data/raw/GIDIAS_metadata_20250507.xlsx")

In [33]:
df_meta.head()

,Column,Variable,Format,Number or range of unique entries,Explanation,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,...,Unnamed: 13,Unnamed: 14,Unnamed: 15,Unnamed: 16,Unnamed: 17,Unnamed: 18,Unnamed: 19,Unnamed: 20,Unnamed: 21,Unnamed: 22
0,A,rowID,Numeric,22865,Numeric ID of impact record,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,B,UniqueID,Text,Free text,"Unique identifier of impact records, indicatin...",NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,C,IAS.Species.Name,Text,3779,Name of invasive alien species (IAS) as assign...,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,D,Verified.Name.GBIF.Taxon,Text,3354,"Species name of IAS, or higher taxonomic level...",NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,E,GBIF.scientificName.with.author,Text,3205,Species name with author and year of descripti...,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [43]:
df_meta.columns

Index(['Column', 'Variable', 'Format', 'Number or range of unique entries',
       'Explanation', 'Unnamed: 5', 'Unnamed: 6', 'Unnamed: 7', 'Unnamed: 8',
       'Unnamed: 9', 'Unnamed: 10', 'Unnamed: 11', 'Unnamed: 12',
       'Unnamed: 13', 'Unnamed: 14', 'Unnamed: 15', 'Unnamed: 16',
       'Unnamed: 17', 'Unnamed: 18', 'Unnamed: 19', 'Unnamed: 20',
       'Unnamed: 21', 'Unnamed: 22'],
      dtype='str')

In [44]:
df_bool = df_raw.select_dtypes(include= "bool").columns.to_list()
df_meta[df_meta["Variable"].isin(df_bool)]

,Column,Variable,Format,Number or range of unique entries,Explanation,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,...,Unnamed: 13,Unnamed: 14,Unnamed: 15,Unnamed: 16,Unnamed: 17,Unnamed: 18,Unnamed: 19,Unnamed: 20,Unnamed: 21,Unnamed: 22
21,V,Peer.reviewed,Logical,2,Whether or not the source was peer-reviewed,True,False,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
27,AB,Island.k,Logical,2,Whether the location was on an island,True,False,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
29,AD,Protected.area.k,Logical,2,Whether the location was in a protected area,True,False,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
40,AO,global.extinction,Logical,2,Whether the impact led to a global extinction ...,True,False,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
52,BA,UoA.Dry,Logical,2,Unit of Analysis: dummy variable indicating if...,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
53,BB,UoA.Boreal,Logical,2,Unit of Analysis: dummy variable indicating if...,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
54,BC,UoA.Mediterranean,Logical,2,Unit of Analysis: dummy variable indicating if...,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
55,BD,UoA.Tundra,Logical,2,Unit of Analysis: dummy variable indicating if...,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
56,BE,UoA.Savanna,Logical,2,Unit of Analysis: dummy variable indicating if...,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
57,BF,UoA.Grassland,Logical,2,Unit of Analysis: dummy variable indicating if...,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
58,BG,UoA.Desert,Logical,2,Unit of Analysis: dummy variable indicating if...,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
59,BH,UoA.Urban,Logical,2,Unit of Analysis: dummy variable indicating if...,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
60,BI,UoA.Cultivated,Logical,2,Unit of Analysis: dummy variable indicating if...,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
61,BJ,UoA.Aquaculture,Logical,2,Unit of Analysis: dummy variable indicating if...,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
62,BK,UoA.Wetland,Logical,2,Unit of Analysis: dummy variable indicating if...,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
63,BL,UoA.Surface,Logical,2,Unit of Analysis: dummy variable indicating if...,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
64,BM,UoA.Shelf,Logical,2,Unit of Analysis: dummy variable indicating if...,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
65,BN,UoA.Ocean,Logical,2,Unit of Analysis: dummy variable indicating if...,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
66,BO,UoA.Coastal,Logical,2,Unit of Analysis: dummy variable indicating if...,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
67,BP,NCP.Habitat,Logical,2,Nature's Contributions to People: dummy variab...,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
68,BQ,NCP.Pollination,Logical,2,Nature's Contributions to People: dummy variab...,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
69,BR,NCP.AirQuality,Logical,2,Nature's Contributions to People: dummy variab...,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
70,BS,NCP.Climate,Logical,2,Nature's Contributions to People: dummy variab...,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
71,BT,NCP.OceanAcid,Logical,2,Nature's Contributions to People: dummy variab...,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
72,BU,NCP.Freshwater,Logical,2,Nature's Contributions to People: dummy variab...,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
73,BV,NCP.WaterQuality,Logical,2,Nature's Contributions to People: dummy variab...,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
74,BW,NCP.Soils,Logical,2,Nature's Contributions to People: dummy variab...,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
75,BX,NCP.Hazards,Logical,2,Nature's Contributions to People: dummy variab...,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
76,BY,NCP.BiolProcess,Logical,2,Nature's Contributions to People: dummy variab...,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
77,BZ,NCP.Energy,Logical,2,Nature's Contributions to People: dummy variab...,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
78,CA,NCP.Food,Logical,2,Nature's Contributions to People: dummy variab...,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
79,CB,NCP.Materials,Logical,2,Nature's Contributions to People: dummy variab...,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
80,CC,NCP.Medicinal,Logical,2,Nature's Contributions to People: dummy variab...,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
81,CD,NCP.Learning,Logical,2,Nature's Contributions to People: dummy variab...,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
82,CE,NCP.Physical,Logical,2,Nature's Contributions to People: dummy variab...,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
83,CF,NCP.Identities,Logical,2,Nature's Contributions to People: dummy variab...,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
84,CG,NCP.Options,Logical,2,Nature's Contributions to People: dummy variab...,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
85,CH,CWB.Safety,Logical,2,Constituents of Well-being: dummy variable ind...,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
86,CI,CWB.Assets,Logical,2,Constituents of Well-being: dummy variable ind...,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
87,CJ,CWB.Health,Logical,2,Constituents of Well-being: dummy variable ind...,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
88,CK,CWB.Relations,Logical,2,Constituents of Well-being: dummy variable ind...,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
89,CL,CWB.Freedom,Logical,2,Constituents of Well-being: dummy variable ind...,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

### Summary 3 - Taking a look at the metadata
Afer reviewing the metadata the columns, that could be interesting for the analysis are the following: 
- `Island.k`
- `Protected.area.k`
- `global.extinction`

---
## 4. Data quality
The quality of the data will be asseset in the next part. 
(Missing values, duplicates, numbers stored as text, dates stored as strings. Write down what you find — this is the to-do list for notebook 02.)

In [49]:
df_raw.isna().sum()

rowID                                 0
UniqueID                              0
IAS.Species.Name                      0
Verified.Name.GBIF.Taxon            519
GBIF.scientificName.with.author    1291
                                   ...
CWB.Safety                            0
CWB.Assets                            0
CWB.Health                            0
CWB.Relations                         0
CWB.Freedom                           0
Length: 90, dtype: int64

Some columns appear to contain null values. It is important to identify which columns contain these values in order to determine how they should be handled during the data-cleaning process.

In [50]:
df_raw.isna().sum()[df_raw.isna().sum() > 0]

Verified.Name.GBIF.Taxon                519
GBIF.scientificName.with.author        1291
Genus                                   557
Family                                  584
Order                                   664
Class                                  1922
Phylum                                  555
Kingdom                                 526
IAS.Functional.Group                   3178
native.range.of.IAS                   17412
Text.excerpt                           4147
DOI                                   16507
Year                                    672
Year.of.impact                        19911
Type.of.source                         1718
Language                                764
Methodology.details                    2781
Region                                  131
Country.Location                       1249
Island                                14863
Protected.area                        19632
Realm                                    73
Units.of.Analysis.clean                3322
Spatial.scale                          4500
Affected.native.species.Details        8507
Affected.native.species.Taxon          8485
Affected.ecosystem.property            9548
investigated.level.of.organization    12300
mechanism.Nature.clean                 8796
direction.Nature                       8191
direct.or.indirect.Nature             12493
magnitude.Nature                      10984
affected.NCP.clean                    15571
details.NCP                           19176
direction.NCP                         15721
magnitude.NCP                         19900
affected.CWB.clean                    19427
details.CWB                           20160
direction.CWB                         19465
magnitude.CWB                         21270
magnitude.CWB.details                 22672
IPLC                                  22081
dtype: int64

check if columns with a lot of nas are necessary

Check if all types of data are right, from groups for each data type, espacially for  numerical string data
check if dates stored as string

Years are of type float and should be of type date.

### Summary 4. Data quality 
An important part of the data processing will be to standardise the column names and ensure a consistent naming convention.
Null values can be kept in the dataset. Removing a null value would implicate removing the entire row. Depending on the reserch question and the column the null value is in, it should be decided if the value and tehrefore the row can be kept or not. 
The type of the dates should be changed from float to data.

---
## 5. Categorical columns

**This is the section that feeds tomorrow.** A column with few distinct values repeated over many rows is a lookup table waiting to happen. Find them.

---
## 6. Research questions

1. When where invasive species introduces the most? Is there a time where introduction of invasive species boomed?
2. Which countrys are the most impacted by invasive species?
3. Which species has the greater impact?

---
## 7. Into notebook 02

The tables you are going to build, and the problems you have to fix first.